name: CI tests

on:
  push:
    branches: ["main", "test"]

  pull_request:
    branches: ["main"]

jobs:
  CI-tests:
    runs-on: ubuntu-latest

    steps:
      - name: echo event
        run: |
          echo "${{ github.event_name }}"
          echo ${{ github.repository }}