name: CI tests

on:
  push:
    branches: ["main", "test"]

  pull_request:
    branches: ["main"]

jobs:
  CI-tests:
    runs-on: ubuntu-latest

    steps:
      - name: echo event
        environment: ${{ vars.ENVIRONMENT_STAGE }}
        run: |
          echo "${{ vars.GITHUB_EVENT_NAME }}"
          echo ${{ github.repository }}