name: CI tests

on:
  push:
    branches: ["main", "test"]

  pull_request:
    branches: ["main"]

jobs:
  CI-tests:
    runs-on: ubuntu-latest

    steps:
      - name: echo event
        if: ${{ github.event_name == 'push' }}
        run: echo this is a push event

      - name: another echo event
        if: ${{ github.event_name == 'pull_request' }}
        run: echo this is a pull_request event